#changed yml for frontend this is docker-compose.yml for dspace-angular -production only

services:
  dspace-angular:
    container_name: dspace-angular
    environment:
      DSPACE_UI_SSL: 'false'
      DSPACE_UI_HOST: elibrary.dimtmw.com
      DSPACE_UI_PORT: '4100'
      DSPACE_UI_NAMESPACE: /
      DSPACE_REST_SSL: 'false'
      DSPACE_REST_HOST: elibrary.dimtmw.com
      DSPACE_REST_PORT: 8080
      DSPACE_REST_NAMESPACE: /server
      NODE_OPTIONS: "--max_old_space_size=6144"
    build:
      context: ..
      dockerfile: Dockerfile
    networks:
      - dspacenet
    ports:
      - "4100:4100"
      - "9900:9876"
    stdin_open: true
    tty: true
    volumes:
      - ../:/app

networks:
  dspacenet: {}
